### ISSUE TITLE
Names with wrong charset

### ISSUE THREAD

**Issue by Daviex** [GwentAPI/gwentapi#20]
Hey.

I'm using your api, but I noticed something:

Some names, like the ALZUR’S DOUBLE CROSS, has wrong charset printed into the web, in fact, you can't print out the quote char, by giving back some strange characters.

Thanks for your work

EDIT:
Added an example:
https://api.gwentapi.com/v0/cards/qH0Xa6r3RjiKeaSbeEX4Cg

The name has wrong charset as you can see.

**Comment by Tri125** [comment]
Thanks for the report.

The charset is UTF-8 and I believe the character is the [right single quotation mark (U+2019)](http://www.fileformat.info/info/unicode/char/2019/index.htm). Verify with the charset used by your decoder if you can get it to print correctly.

On my side I'm able to get it correctly decoded with different clients (curl, the Postman chrome plugin, etc.). I've noticed that visiting the pages straight with a web browser produce the following: "Alzurâ€™s Double". Maybe some clients are smart enough to detect the charset automatically but not others. It seems that I don't set the charset on the content-type header so maybe that's the reason browsers are tripping on it.

However, even if you get it to decode correctly, text search will not find any result for "Alzur's" since it's not the same character stored in the database. I don't have an ETA but probably less than a day to fix it if everything goes well but I won't release the new version until #11 is ready.

**Comment by Tri125** [comment]
I can confirm that setting the appropriate charset in the content-header field fix the browser behavior that I reported.

**Comment by Daviex** [comment]
I got same problem by using a Python script to analyze the JSON, it can't decode this too as a quote character.

Did you tried to set the Content-Type of the page into the header as UTF-8? That could maybe be a fix?

Thanks for your work, While using it, If I find a bug and I can fix it, I will try to help!

EDIT: 
Nothing, readed an email, didn't readed the next email with your second reply, we reached same conclusion.

**Comment by Tri125** [comment]
Charset is being correctly set as of bb5e59120f0b16e9e345a99bae61ebe6dc05595e.
I will still look into storing the ascii equivalent character in the db as it prevents correct search with the search by name endpoint but this is less than a priority over making sure that all clients can correctly decode every text in the API.  :laughing: 

I will keep you posted when the bb5e59 goes in production (in 1-2 days maybe). I'm bundling several minor API change together.

**Comment by Daviex** [comment]
Perfect 💪

**Comment by Tri125** [comment]
The new version has entered production. Enjoy!
[Patch note](https://github.com/GwentAPI/gwentapi/releases/tag/v0.5.6)

**Comment by Daviex** [comment]
Perfect! Thanks
