### ISSUE TITLE
Some cards are missing certain properties

### ISSUE THREAD

**Issue by zhouzi** [GwentAPI/gwentapi#33]
That may be intentional but some cards doesn't have certain properties. For example, [Alba Spearmen](https://api.gwentapi.com/v0/cards/Up9mM6SDUuqH4tNx7p0q9g) doesn't have `categories` although [Adrenaline Rush](https://api.gwentapi.com/v0/cards/_SIFOcYAVMqjbIi8HKVS9w) does.

I'd suggest to set it to an empty array instead of removing it.

**Comment by Tri125** [comment]
It's intended and [documented](https://gwentapi.com/swagger/index.html#/definitions/GwentapiCard).

faction, group, href, name, uuid, and variations are guaranteed to be part of the object, the rest are optional.

I don't think there's a strong semantic reason to make an empty array, I think it communicate the same intention if it's missing entirely.

If there's not a strong semantic reason I leave out the field since it would otherwise use memory and consume a tiny bit more bandwidth to create the object for 0 benefit.

**Comment by Tri125** [comment]
This is, of course, up for discussion.

**Comment by zhouzi** [comment]
Having default empty values makes it easier to consume as you can loop over the cards and treat them all the same. But it's no big deal and I'm fine with it 👍
