### ISSUE TITLE
Automation of new version deployment.

### ISSUE THREAD

**Issue by Tri125** [GwentAPI/gwentapi#4]

**Comment by Tri125** [comment]
As of ef8884899dea7e847456301dc3397678915e60dd the initial database process is somewhat automated. It's still ineffective when updating the data and is not capable of automating a deployment of the go code.

**Comment by GuiSim** [comment]
Would you guys be interested in using Terraform (https://www.terraform.io/) for deployment?

At the moment, does everything (server + database + cache[?]) live on the same server?

**Comment by Tri125** [comment]
Yeah, there's only one server at the moment with the web server, app, and database (mongodb now).
CloudFlare handles all of the current caching need.

I will have to look on how to best scale it sooner than later but I have no experience in that sort of thing, this is my first public web app. I currently don't have a way to quickly deploy a new version of gwentapi or a way to quickly reproduce the current server.

I've been directed toward Kubernetes with Dockers, any thought on that?

**Comment by GuiSim** [comment]
My suggestion was mostly about automatic deployment, not scalability.

For scalability, since the website is mostly static, I think the current solution should easily scale. CloudFlare will probably handle 99% of all requests after a short while.

Docker is always useful. It would allow you to trivially move your database to another server if you choose to. K8S is way overkill for your needs IMO. It is however a great tool and worth playing around with if only for learning it.

**Comment by Tri125** [comment]
I'm a bit late on commenting to this but as of the 9th of April I've been working with Ansible and the automation is on its way. The reasons I decided to use Ansible is because the tool is well documented, agentless, and easy to learn. It's capable of creating new machines and configuring them, as well as deploying new versions of the app to the machines.

I didn't opted for Terraform because it seems to have been made mainly to provision servers. Its benefits would have been lost to me since the infrastructure of gwentapi is very minimal.
